<!DOCTYPE HTML>
<html lang="eng">
<head>	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">
	<meta name="Megafun file-sharing site">
	<title><?= htmlspecialchars($data[0]['orig_name']) ?></title>
	<link href="/css/pure.css" rel="stylesheet" type="text/css">
</head>
<body>
<h1>Megafun-share</h1>
<hr>
<h2><?= htmlspecialchars($data[0]['orig_name']) ?></h2>
<form action="<?php $_SERVER['PHP_SELF']?>" method="POST">
	<input type="submit" value="Download">
</form>
<? if(!is_null($data[0]['preview_path'])): ?>
<img src="../<?= htmlspecialchars($data[0]['preview_path']) ?>" alt="image preview">
<? endif; ?>
<hr>
<? if(!empty($data[0]['commentary'])): ?>
<p><?= $data[0]['commentary'] ?></p>
<? endif; ?>
<hr>
<table>
	<tr>
		<td>Upload date:</td>
		<td><?= htmlspecialchars($data[0]['timestamp']) ?></td>
	</tr>
	<tr>
		<td>File type:</td>
		<td><?= htmlspecialchars($data[0]['mime_type']) ?></td>
	</tr>
	<? if(!is_null($data[0]['metadata'])): ?>
	<? foreach($data[0]['metadata'] as $key => $value): ?>
	<tr>
		<td><?= htmlspecialchars($key) ?>:</td>
		<td><?= htmlspecialchars($value) ?></td>
	</tr>
	<? endforeach; ?>
	<? endif; ?>
</table>
</body>
</html>