<!DOCTYPE HTML>
<html lang="eng">
<head>	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">
	<meta name="Megafun file-sharing site">
	<title>Megafun-share</title>
	<link href="/css/pure.css" rel="stylesheet" type="text/css">
</head>
<body>
<h1>Megafun-share</h1>
<hr>
<form action="<?php $_SERVER['PHP_SELF']?>" enctype="multipart/form-data" method="POST">
	Select your file:
	<input type="file" name="file">
	<input type="submit" value="Upload">
</form>

</div>
</body>
</html>