<!DOCTYPE HTML>
<html lang="eng">
<head>	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">
	<meta name="Megafun file-sharing site">
	<meta http-equiv="refresh" content="3;<?= $data['new_name'] ?>" >
	<title>Successfull upload</title>
	<link href="/css/pure.css" rel="stylesheet" type="text/css">
</head>
<body>
<h1>Megafun-share</h1>
<hr>
<h2>File <?= $data['name'] ?> was successfully uploaded.</h2>
</body>
</html>